# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a21144c57e37e49a28c6a012e45acb0334a71e90c7ce55f009cfc3e46583211944b3856478edb4071c1c7cc8a7e1f4fcd6387e6c7cac80250b6dc6b859657f93

test:
  secret_key_base: ff5685e2838b2805fa43cacbe858a32db9412fe6733edd437564676f355f9424efcb29eae88911f7e41db7406721dd4533064a396d19ddfd280957a0acfcedb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
